### ISSUE TITLE
Retaining Layout

### ISSUE THREAD

**Issue by VA-01** [felbsn/NetDock.WPF#1]
Could you point me in a general direction on what to do to save the layout of all the windows and reload them. Great control, thanks. I'm currently saving obvious properties like surface height, width, flowdirection etc but this isn't enough.

**Comment by felbsn** [comment]
hi, you can look at this version [NetDock](https://github.com/felbsn/NetDock). its kind of battle tested. 

also it has built-in save & load method
```csharp
var xml = docksurface.ToXml();
// ...  some time after 
docksurface.FromXml(xml);
```
